import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { CheckCircle2, XCircle, Lock, Shield, Mail } from "lucide-react";
import { motion } from "framer-motion";

const WHAT_IT_DOES = [
  "Organizes and categorizes evidence entries from uploaded documents and text",
  "Identifies potential evidentiary relevance based on common custody legal factors",
  "Analyzes communication patterns and response statistics from imported messages",
  "Generates structured drafts of legal documents for attorney review",
  "Builds organized exhibit packets for court preparation",
  "Provides informational context about common custody factor categories",
];

const WHAT_IT_DOES_NOT = [
  "Provide legal advice or establish an attorney-client relationship",
  "Guarantee any legal outcome or predict court decisions",
  "Replace the judgment of a licensed family law attorney",
  "Constitute an attorney-client privilege",
  "Provide jurisdiction-specific legal guidance beyond general informational context",
  "Serve as a substitute for professional legal representation",
];

export default function HelpAndDisclaimer() {
  return (
    <div className="max-w-2xl mx-auto space-y-6">
      <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}>
        <h1 className="text-xl font-bold">Help & Legal Notice</h1>
        <p className="text-sm text-muted-foreground mt-1">Understanding what this app does and does not do.</p>
      </motion.div>

      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-sm flex items-center gap-2">
            <CheckCircle2 className="h-4 w-4 text-emerald-600 dark:text-emerald-400" />
            What CaseClear Does
          </CardTitle>
        </CardHeader>
        <CardContent>
          <ul className="space-y-2">
            {WHAT_IT_DOES.map((item, i) => (
              <li key={i} className="flex items-start gap-2 text-sm">
                <CheckCircle2 className="h-4 w-4 text-emerald-600 dark:text-emerald-400 mt-0.5 shrink-0" />
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </CardContent>
      </Card>

      <Card className="border-destructive/20">
        <CardHeader className="pb-3">
          <CardTitle className="text-sm flex items-center gap-2 text-destructive">
            <XCircle className="h-4 w-4" />
            What This App Does NOT Do
          </CardTitle>
        </CardHeader>
        <CardContent>
          <ul className="space-y-2">
            {WHAT_IT_DOES_NOT.map((item, i) => (
              <li key={i} className="flex items-start gap-2 text-sm">
                <XCircle className="h-4 w-4 text-destructive mt-0.5 shrink-0" />
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </CardContent>
      </Card>

      <Card className="border-primary/20 bg-primary/5">
        <CardContent className="p-4">
          <p className="text-sm font-semibold mb-2">Legal Disclaimer</p>
          <p className="text-xs text-muted-foreground leading-relaxed">
            CaseClear is an organizational and informational tool. All content generated by this application, including evidence summaries, factor analysis, document drafts, and any other output, is provided for informational and organizational purposes only.
          </p>
          <p className="text-xs text-muted-foreground leading-relaxed mt-2">
            Nothing in this application constitutes legal advice, creates an attorney-client relationship, or should be relied upon as a substitute for consultation with a qualified, licensed attorney. Family law is complex and jurisdiction-specific. The application of any legal information to your specific situation requires professional legal judgment.
          </p>
          <p className="text-xs text-muted-foreground leading-relaxed mt-2">
            <strong>You should always consult with a licensed family law attorney in your jurisdiction before making any legal decisions, filing any court documents, or relying on any information generated by this application.</strong>
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-sm flex items-center gap-2">
            <Shield className="h-4 w-4 text-primary" />
            Privacy & Security
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          {[
            { icon: Lock, label: "End-to-end encrypted", description: "Your case data is encrypted at rest and in transit." },
            { icon: Shield, label: "Private to your account", description: "No one but you can access your case data." },
            { icon: Shield, label: "Never sold or shared", description: "Your data is never sold, shared, or used to train AI models." },
          ].map(({ icon: Icon, label, description }) => (
            <div key={label} className="flex items-start gap-3">
              <Icon className="h-4 w-4 text-primary mt-0.5 shrink-0" />
              <div>
                <p className="text-sm font-medium">{label}</p>
                <p className="text-xs text-muted-foreground">{description}</p>
              </div>
            </div>
          ))}
        </CardContent>
      </Card>

      <Separator />

      <div className="flex items-center gap-3">
        <Mail className="h-4 w-4 text-muted-foreground" />
        <div>
          <p className="text-sm font-medium">Support</p>
          <p className="text-xs text-muted-foreground">support@familycourtcompanion.ai</p>
        </div>
      </div>

      <p className="text-xs text-muted-foreground text-center">CaseClear · Version 1.0.0 · © 2026</p>
    </div>
  );
}
